# Standards: 0.11
---
  - name: "Creating a variable of all benchmark files"
    find:
      paths: "./level-1/"
      file_type: file
      patterns: ['*.yml']
    register: file

  - name: "Executing all benchmarks in directory"
    include: "{{ item.path }}"
    when: "item.path.split('/')[-1]|regex_replace('.yml','') not in cis_level_1_exclusions"
    with_items: "{{ file.files }}"
  
